services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codigodelsur-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - db_data:/app/src/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
